stages:
  download_data:
    cmd: python3.7 components/data_processor/download_data.py
    params:
      - data_downloading
      - data_processor
    deps:
      - components/data_processor
    outs:
      - data/downloaded

  prepare_training_data:
    cmd: python3.7 components/data_processor/prepare_training_data.py
    params:
      - data_processor
    deps:
      - components/data_processor
      - data/downloaded
    outs:
      - data/training
